[package]
name = "rust_api_client"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.200"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "0.12.23", features = ["json"] }
thiserror = "2.0.17"
